version: 2
jobs:
    build:
        working_directory: ~/typedec
        docker:
          - image: circleci/node:10.17.0

        steps:
          - checkout

          - restore_cache:
                keys:
                  - v1-node_modules-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}
                  - v1-node_modules-{{ checksum "package.json" }}-
                  - v1-node_modules-

          - run:
              name: Install Dependencies
              command: npm install

          - save_cache:
              key: v1-node_modules-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}
              paths:
                - node_modules

          - run:
              name: Setup Code Climate test-reporter
              command: |
                  curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
                  chmod +x ./cc-test-reporter

          - run:
              name: Run Linter
              command: npm run lint

          - run:
              name: Run Tests
              command: |
                    ./cc-test-reporter before-build
                    npm run test:ci
                    ./cc-test-reporter after-build --exit-code $?
